      - name: Configure kernel
        run: |
          cd gta9
          export PATH=$HOME/toolchain/clang/bin:$PATH
          make O=out ARCH=arm64 gta9_00_defconfig
          # Gabungkan overlay config vendor (di sinilah konfigurasi display/GPU berada)
          make O=out ARCH=arm64 entry_level.config ot11.config ot11_data.config ot11_wifi.config
          # KernelSU + pendukung
          scripts/config --file out/.config \
            -e CONFIG_KSU \
            -e CONFIG_KPROBES \
            -e CONFIG_HAVE_KPROBES \
            -e CONFIG_OVERLAY_FS
          scripts/config --file out/.config \
            --set-str CONFIG_LOCALVERSION "-KSU-${{ steps.ksu_info.outputs.ksu_version }}" \
            --disable CONFIG_LOCALVERSION_AUTO
          scripts/config --file out/.config \
            -e CONFIG_CGROUPS \
            -e CONFIG_BLK_CGROUP
          sed -i 's/^CONFIG_WERROR=y/CONFIG_WERROR=n/g' out/.config
          make O=out ARCH=arm64 olddefconfig
          echo "Configuration complete."
